development:
 adapter: mysql2
 encoding: utf8
 database: ShopOnline_aa
 pool: 5
 username: root
 password: pass

test:
 adapter: mysql2
 encoding: utf8
 database: ShopOnline_aa_test
 pool: 5
 username: root
 password: pass


production:
 adapter: mysql2
 encoding: utf8
 database: ShopOnline_aa_production
 pool: 5
 username: root
 password: pass